### PR TITLE
test: fix main-page tcs to support sample app

### PR DESCRIPTION
**Pull request by Wennio-Oliveira**
# Description

Fix main page test cases and delete user-page test cases

# How Has This Been Tested?

It was tested locally

## Checklist

- [ x ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

user-page test cases were deleted because this page is not validate for the repository

### CODE REVIEW

**Comment by RMCampos** [comment]
@Wennio-Oliveira I think would be great to have the cypress command in the `package.json` file :)

**Review by RMCampos — APPROVED** [review]
Great job! 🥳

**Review by annibalsilva — CHANGES_REQUESTED** [review]
The smoke test is sound, but it fails due to what seem to be failures of redirection in the development environment.

MicrosoftTeams-image (1)

The test loses its usefulness with this behaviour: we should either not execute it in the development environment or fix the redirection issue there.

**Review by annibalsilva — APPROVED** [review]

**Review by annibalsilva — CHANGES_REQUESTED** [review]
Pipeline's still broken. Can we skip the user page tests for now? From what I gather, we're not going to log in during the smoke tests, so we can't even get to that page during them.

**Review by annibalsilva — APPROVED** [review]

**Pull request merged**
